# Generated by Django 5.2.6 on 2025-09-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_products_numreviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='_id',
        ),
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
